-- Create profiles table
create table profiles (
  id uuid references auth.users on delete cascade primary key,
  first_name text,
  last_name text,
  email text unique,
  squadron text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create board applications table
create table board_applications (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  position text check (position in ('president', 'member')) not null,
  status text check (status in ('pending', 'approved', 'rejected')) default 'pending',
  board_month text not null,
  board_year integer not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Set up row level security
alter table profiles enable row level security;
alter table board_applications enable row level security;

-- Create policies
create policy "Public profiles are viewable by everyone"
  on profiles for select
  using ( true );

create policy "Users can insert their own profile"
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile"
  on profiles for update
  using ( auth.uid() = id );

create policy "Anyone can insert applications"
  on board_applications for insert
  with check ( true );

create policy "Applications are viewable by everyone"
  on board_applications for select
  using ( true );